services:
  postgres:
    image: postgres:16-alpine
    container_name: pokemanager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pokemanager-data:/var/lib/postgresql/data

volumes:
  pokemanager-data: