export const NATURE_LABELS_PT = {
  HARDY: 'Forte',
  LONELY: 'Solitária',
  BRAVE: 'Corajosa',
  ADAMANT: 'Firme',
  NAUGHTY: 'Travessa',
  BOLD: 'Ousada',
  DOCILE: 'Dócil',
  RELAXED: 'Relaxada',
  IMPISH: 'Sapeca',
  LAX: 'Frouxa',
  TIMID: 'Tímida',
  HASTY: 'Apressada',
  SERIOUS: 'Séria',
  JOLLY: 'Alegre',
  NAIVE: 'Ingênua',
  MODEST: 'Modesta',
  MILD: 'Branda',
  QUIET: 'Quieta',
  BASHFUL: 'Envergonhada',
  RASH: 'Precipitada',
  CALM: 'Calma',
  GENTLE: 'Gentil',
  SASSY: 'Atrevida',
  CAREFUL: 'Cautelosa',
  QUIRKY: 'Excêntrica',
}